{% set name = "pyobjc-framework-CoreServices" %}
{% set version = "10.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyobjc_framework_coreservices-{{ version }}.tar.gz
  sha256: ee3cf8379839efe4300bbd33dca204ebe873e2671160fff856569976d45c68a8

build:
  skip: true  # [not osx or py2k or python_impl == 'pypy' or (arm64 and py < 39)]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pyobjc-core {{ version }}
    - pyobjc-framework-fsevents {{ version }}

test:
  imports:
    - CoreServices
    - CoreServices.CarbonCore
    - CoreServices.DictionaryServices
    - CoreServices.LaunchServices
    - CoreServices.Metadata
    - CoreServices.SearchKit
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the “CoreServices” framework on macOS.
  description: |
    The PyObjC project aims to provide a bridge between the Python and
    Objective-C programming languages on macOS. The bridge is intended to be
    fully bidirectional, allowing the Python programmer to take full advantage
    of the power provided by various Objective-C based toolkits and the
    Objective-C programmer transparent access to Python based functionality.
  license: MIT
  license_family: MIT
  license_file: License.txt
  doc_url: https://pyobjc.readthedocs.io/
  dev_url: https://github.com/ronaldoussoren/pyobjc

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - dalthviz
    - steff456
