{% set name = "pyobjc-framework-CoreServices" %}
{% set version = "9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6e80770ead727979e9ffd4ea97c30889e1fdec49873bb5129bf3ef3c5b90005
  patches:
    - patches/0001-Remove-werror-from-compile-flags.patch

build:
  skip: true  # [not osx]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - pyobjc-core {{ version }}
    - pyobjc-framework-fsevents {{ version }}

test:
  imports:
    - CoreServices
    - CoreServices.CarbonCore
    - CoreServices.DictionaryServices
    - CoreServices.LaunchServices
    - CoreServices.Metadata
    - CoreServices.SearchKit
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ronaldoussoren/pyobjc
  summary: Wrappers for the “CoreServices” framework on macOS.
  description: |
    The PyObjC project aims to provide a bridge between the Python and
    Objective-C programming languages on macOS. The bridge is intended to be
    fully bidirectional, allowing the Python programmer to take full advantage
    of the power provided by various Objective-C based toolkits and the
    Objective-C programmer transparent access to Python based functionality.
  license: MIT
  license_family: MIT
  license_file: License.txt
  doc_url: https://pyobjc.readthedocs.io/
  dev_url: https://github.com/ronaldoussoren/pyobjc

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - dalthviz
    - steff456
